### ISSUE TITLE
You just broke it

### ISSUE THREAD

**Issue by k1ng440** [AuraEQ/laravel-multi-tenant#76]
Hello, i am using 5.1 LTS and this is the error i am getting now

```
  [RuntimeException]
  Error Output: PHP Fatal error:  Interface 'Illuminate\Database\Eloquent\Scope' not found in /home/vagrant/vdyo5/vendor/aura-is-here/laravel-multi-tenant/src/TenantScope.php on line 11
  PHP Stack trace:
  PHP   1. {main}() /home/vagrant/vdyo5/artisan:0
  PHP   2. Illuminate\Foundation\Console\Kernel->handle() /home/vagrant/vdyo5/artisan:36
  PHP   3. Symfony\Component\Console\Application->run() /home/vagrant/vdyo5/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:107
  PHP   4. Symfony\Component\Console\Application->doRun() /home/vagrant/vdyo5/vendor/symfony/console/Application.php:120
  PHP   5. Symfony\Component\Console\Application->doRunCommand() /home/vagrant/vdyo5/vendor/symfony/console/Application.php:189
  PHP   6. Illuminate\Console\Command->run() /home/vagrant/vdyo5/vendor/symfony/console/Application.php:841
  PHP   7. Symfony\Component\Console\Command\Command->run() /home/vagrant/vdyo5/vendor/laravel/framework/src/Illuminate/Console/Command.php:136
  PHP   8. Illuminate\Console\Command->execute() /home/vagrant/vdyo5/vendor/symfony/console/Command/Command.php:256
  PHP   9. Illuminate\Container\Container->call() /home/vagrant/vdyo5/vendor/laravel/framework/src/Illuminate/Console/Command.php:150
  PHP  10. call_user_func_array:{/home/vagrant/vdyo5/vendor/laravel/framework/src/Illuminate/Container/Container.php:507}() /home/vagrant/vdyo5/vendor/laravel/framework/src/Illuminate/Container/Container.php:507
  PHP  11. Barryvdh\LaravelIdeHelper\Console\GeneratorCommand->fire() /home/vagrant/vdyo5/vendor/laravel/framework/src/Illuminate/Container/Container.php:507
  PHP  12. Barryvdh\LaravelIdeHelper\Generator->generate() /home/vagrant/vdyo5/vendor/barryvdh/laravel-ide-helper/src/Console/GeneratorCommand.php:113
  PHP  13. Barryvdh\LaravelIdeHelper\Generator->generatePhpHelper() /home/vagrant/vdyo5/vendor/barryvdh/laravel-ide-helper/src/Generator.php:71
  PHP  14. Barryvdh\LaravelIdeHelper\Generator->getNamespaces() /home/vagrant/vdyo5/vendor/barryvdh/laravel-ide-helper/src/Generator.php:81
  PHP  15. Barryvdh\LaravelIdeHelper\Alias->__construct() /home/vagrant/vdyo5/vendor/barryvdh/laravel-ide-helper/src/Generator.php:178
  PHP  16. Barryvdh\LaravelIdeHelper\Alias->detectRoot() /home/vagrant/vdyo5/vendor/barryvdh/laravel-ide-helper/src/Alias.php:45
  PHP  17. Illuminate\Support\Facades\Facade::getFacadeRoot() /home/vagrant/vdyo5/vendor/barryvdh/laravel-ide-helper/src/Alias.php:189
  PHP  18. Illuminate\Support\Facades\Facade::resolveFacadeInstance() /home/vagrant/vdyo5/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:120
  PHP  19. Illuminate\Container\Container->offsetGet() /home/vagrant/vdyo5/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:151
  PHP  20. Illuminate\Foundation\Application->make() /home/vagrant/vdyo5/vendor/laravel/framework/src/Illuminate/Container/Container.php:1163
  PHP  21. Illuminate\Container\Container->make() /home/vagrant/vdyo5/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:674
  PHP  22. Illuminate\Container\Container->build() /home/vagrant/vdyo5/vendor/laravel/framework/src/Illuminate/Container/Container.php:631
  PHP  23. AuraIsHere\LaravelMultiTenant\LaravelMultiTenantServiceProvider->AuraIsHere\LaravelMultiTenant\{closure}() /home/vagrant/vdyo5/vendor/laravel/framework/src/Illuminate/Container/Container.php:738
  PHP  24. spl_autoload_call() /home/vagrant/vdyo5/vendor/laravel/framework/src/Illuminate/Container/Container.php:32
  PHP  25. Composer\Autoload\ClassLoader->loadClass() /home/vagrant/vdyo5/vendor/laravel/framework/src/Illuminate/Container/Container.php:32
  PHP  26. Composer\Autoload\includeFile() /home/vagrant/vdyo5/vendor/composer/ClassLoader.php:301
  PHP  27. include() /home/vagrant/vdyo5/vendor/composer/ClassLoader.php:412
  PHP Fatal error:  Uncaught exception 'ErrorException' with message 'Undefined index: function' in /home/vagrant/vdyo5/vendor/raven/raven/lib/Raven/Stacktrace.php:84
  Stack trace:
  #0 /home/vagrant/vdyo5/vendor/raven/raven/lib/Raven/Stacktrace.php(84): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Undefined index...', '/home/vagrant/v...', 84, Array)
  #1 /home/vagrant/vdyo5/vendor/raven/raven/lib/Raven/Client.php(280): Raven_Stacktrace::get_stack_info(Array, true, true, NULL, 1024)
  #2 /home/vagrant/vdyo5/vendor/jenssegers/raven/src/RavenLogHandler.php(64): Raven_Client->captureException(Object(Symfony\Component\Debug\Exception\FatalErrorException), Array)
  #3 /home/vagrant/vdyo5/vendor/jenssegers/raven/src/RavenServiceProvider.php(99): Jenssegers\Raven\RavenLogHandler->log('error', Object(Symfony\Component\Debug\Exception\FatalErrorException), Array)
  #4 [internal function]: Jenssegers\Raven\RavenServiceProvider->Jenssegers\Raven\{closure}('error', Object(Symfony\Component\Debug\Exception\FatalErrorException), Ar in /home/vagrant/vdyo5/vendor/raven/raven/lib/Raven/Stacktrace.php on line 84
  PHP Stack trace:
  PHP   1. {main}() /home/vagrant/vdyo5/artisan:0
  PHP   2. Illuminate\Foundation\Console\Kernel->handle() /home/vagrant/vdyo5/artisan:36
  PHP   3. Symfony\Component\Console\Application->run() /home/vagrant/vdyo5/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:107
  PHP   4. Symfony\Component\Console\Application->doRun() /home/vagrant/vdyo5/vendor/symfony/console/Application.php:120
  PHP   5. Symfony\Component\Console\Application->doRunCommand() /home/vagrant/vdyo5/vendor/symfony/console/Application.php:189
  PHP   6. Illuminate\Console\Command->run() /home/vagrant/vdyo5/vendor/symfony/console/Application.php:841
  PHP   7. Symfony\Component\Console\Command\Command->run() /home/vagrant/vdyo5/vendor/laravel/framework/src/Illuminate/Console/Command.php:136
  PHP   8. Illuminate\Console\Command->execute() /home/vagrant/vdyo5/vendor/symfony/console/Command/Command.php:256
  PHP   9. Illuminate\Container\Container->call() /home/vagrant/vdyo5/vendor/laravel/framework/src/Illuminate/Console/Command.php:150
  PHP  10. call_user_func_array:{/home/vagrant/vdyo5/vendor/laravel/framework/src/Illuminate/Container/Container.php:507}() /home/vagrant/vdyo5/vendor/laravel/framework/src/Illuminate/Container/Container.php:507
  PHP  11. Barryvdh\LaravelIdeHelper\Console\GeneratorCommand->fire() /home/vagrant/vdyo5/vendor/laravel/framework/src/Illuminate/Container/Container.php:507
  PHP  12. Barryvdh\LaravelIdeHelper\Generator->generate() /home/vagrant/vdyo5/vendor/barryvdh/laravel-ide-helper/src/Console/GeneratorCommand.php:113
  PHP  13. Barryvdh\LaravelIdeHelper\Generator->generatePhpHelper() /home/vagrant/vdyo5/vendor/barryvdh/laravel-ide-helper/src/Generator.php:71
  PHP  14. Barryvdh\LaravelIdeHelper\Generator->getNamespaces() /home/vagrant/vdyo5/vendor/barryvdh/laravel-ide-helper/src/Generator.php:81
  PHP  15. Barryvdh\LaravelIdeHelper\Alias->__construct() /home/vagrant/vdyo5/vendor/barryvdh/laravel-ide-helper/src/Generator.php:178
  PHP  16. Barryvdh\LaravelIdeHelper\Alias->detectRoot() /home/vagrant/vdyo5/vendor/barryvdh/laravel-ide-helper/src/Alias.php:45
  PHP  17. Illuminate\Support\Facades\Facade::getFacadeRoot() /home/vagrant/vdyo5/vendor/barryvdh/laravel-ide-helper/src/Alias.php:189
  PHP  18. Illuminate\Support\Facades\Facade::resolveFacadeInstance() /home/vagrant/vdyo5/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:120
  PHP  19. Illuminate\Container\Container->offsetGet() /home/vagrant/vdyo5/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:151
  PHP  20. Illuminate\Foundation\Application->make() /home/vagrant/vdyo5/vendor/laravel/framework/src/Illuminate/Container/Container.php:1163
  PHP  21. Illuminate\Container\Container->make() /home/vagrant/vdyo5/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:674
  PHP  22. Illuminate\Container\Container->build() /home/vagrant/vdyo5/vendor/laravel/framework/src/Illuminate/Container/Container.php:631
  PHP  23. AuraIsHere\LaravelMultiTenant\LaravelMultiTenantServiceProvider->AuraIsHere\LaravelMultiTenant\{closure}() /home/vagrant/vdyo5/vendor/laravel/framework/src/Illuminate/Container/Container.php:738
  PHP  24. spl_autoload_call() /home/vagrant/vdyo5/vendor/laravel/framework/src/Illuminate/Container/Container.php:32
  PHP  25. Composer\Autoload\ClassLoader->loadClass() /home/vagrant/vdyo5/vendor/laravel/framework/src/Illuminate/Container/Container.php:32
  PHP  26. Composer\Autoload\includeFile() /home/vagrant/vdyo5/vendor/composer/ClassLoader.php:301
  PHP  27. include() /home/vagrant/vdyo5/vendor/composer/ClassLoader.php:412

```

**Comment by k1ng440** [comment]
@HipsterJazzbo can you accept this pull request please? https://github.com/AuraEQ/laravel-multi-tenant/pull/77

**Comment by HipsterJazzbo** [comment]
Yeah this will need a few minutes to bring it back down to 4.2 compatibility. I won't have time today, but if someone does a PR I'll merge it

**Comment by k1ng440** [comment]
please accept this too #78

**Comment by illuminate3** [comment]
I totally get not wanting to support older laravel versions and appreciate that you are still accepting pull requests.

thanks!

**Comment by HipsterJazzbo** [comment]
Someone let me know if it works now on 4.2 with #78 merged, and I'll tag a version

**Comment by inctor** [comment]
In regards to Laravel 5.1, i'm not ready yet to upgrade to 5.2, so i'll have to stick with this one for now, but an issue has occured.

I'm not entirely sure what's happening. But for some reason it's not injecting it properly on the models.

I have it configured the usual way, and added the addTenant(); before doing anything database related, but the queries are not updated to include the tenant-scope. Not sure if it's related to the fix in #78 ?

**Comment by inctor** [comment]
Alright, issue found.

The problem is the naming of the config file as far as i can see.

When doing the publish method, it's calling the file "laravel-multi-tenant.php" whereas the code is looking for a file named "tenant.php".

This should resolve my before-mentioned issue :)

**Comment by k1ng440** [comment]
Hello @HipsterJazzbo, can you review and accept #79 please?

**Comment by hipsterjazzbo** [comment]
Sorry, done.

**Comment by k1ng440** [comment]
Hello once again @HipsterJazzbo, please review and accept https://github.com/HipsterJazzbo/laravel-multi-tenant/pull/80

thanks for creating this awesome lib.
